# experiment name
note: Test

# project basic
task: relation 

# model basic
gpu_index: 0
lr: 0.0001
batchsize: 8
epoch: 60
worker: 0
use_sch: True

# dataset
# The path for datasets and annotations
data_folder: data/datasets

trainset: MPII_CLIFF COCO 
testset: Panoptic # GigaCrowd 

model: relation_multimodal # relation_pose_rgb relation_depth_rgb 
use_prior: False

mode: train # train/test

# Use pretrain model and the corresponding path
pretrain: False
pretrain_dir: "/trained model/best_relation_epoch038_104.179420.pkl"

# The name of your training loss function
train_loss: SMPL_Loss Keyp_Loss Mesh_Loss Joint_Loss
test_loss: MPJPE_H36M_instance # MPJPE 

#visualize
viz: False
